import { Aboreto, Poppins } from 'next/font/google';  
import "./globals.css";
import Header from '@/components/Header/Header';
import NextTopLoader from 'nextjs-toploader';


const aboreto = Aboreto({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-aboreto',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${aboreto.variable} ${poppins.variable} antialiased`}>
        <Header />
        {children}
        <NextTopLoader color="#51BB7B" />
      </body>
    </html>
  );
}
